### ISSUE TITLE
Iterative unfolding overview documentation 

### ISSUE THREAD

**Issue by jrbourbeau** [jrbourbeau/pyunfold#21]
We should add a "Unfolding overview" page to the documentation that goes over what unfolding is generally (big picture stuff) and introduces relevant terminology (e.g. "cause bins", "prior").

**Comment by zhampel** [comment]
I put in general big picture stuff, but didn't get to terminology. I will write a subsection in the overview commit I made earlier.

**Comment by jrbourbeau** [comment]
Closed by #30
