### ISSUE TITLE
Pandas dataframes?

### ISSUE THREAD

**Issue by zhampel** [jrbourbeau/pyunfold#45]
Do you think it would be worth to require the use of a single input pandas dataframe that uses something like 'data', 'prior', 'resp', 'eff', 'blocks (groups)' as keywords for numpy arrays? I guess we may not get anything extra out of it cause we're not going to necessarily take much advantage of the pandas functionality.

**Comment by jrbourbeau** [comment]
> I guess we may not get anything extra out of it cause we're not going to necessarily take much advantage of the pandas functionality

That would be my concern too. 

If we were to support a container object for `data`, `efficiencies`, etc. a dictionary would probably make the most sense. That being said, I don't particularly see the need for it. Introducing a container object might just increases the cognitive load of using PyUnfold without much benefit.

**Comment by zhampel** [comment]
I'm going to close this issue because it seems like we agree that there's little benefit of packing in a pandas dataframe.
