### ISSUE TITLE
Covariance matrix calculation  

### ISSUE THREAD

**Issue by jrbourbeau** [jrbourbeau/pyunfold#48]
In theory there are two ways to do the covariance matrix calculation: 

1. Poisson covariance matrix calculation
2. Multinomial covariance matrix calculation

Both these methods are implemented in PyUnfold. However, we currently have the `CovarianceMatrix` class hard coded to only ever use the multinomial covariance calculation. 

https://github.com/jrbourbeau/pyunfold/blob/0a9724b119ad6038b192a63194cff70f2ff6bc21/pyunfold/mix.py#L115-L116

I propose we either:

1. Add this as a parameter to `iterative_unfold` so users can choose between ` "Multinomial"` or `"Poisson"`
2. Drop the Poisson covariance calculation if the existing hard coding of `self.pec_cov_type = "Multinomial"` is there for a good reason. 

What are your thoughts on this @zhampel?

**Comment by zhampel** [comment]
Yeah, I've thought about this in the past as well. The problem is that when simulating a response matrix, you have a fixed number of events falling into a true cause bin. This requires us to use the multinomial form for the covariance matrix. I had left the Poisson there in the case that somehow one could construct the response matrix in a manner that permitted the Poisson form of the covariance calculation. Perhaps we should discuss with Mickael Kuusela to see if he has any suggestions regarding this. For now, is it ok to leave the hard coded version till we have a clearer view?

**Comment by zhampel** [comment]
Thinking about it a little more, perhaps it's even worth it to include a multinomial version of the covariance calculation for the measured data as well. That was it's complete. Again, I'll have to check with M. Kuusela if he can come up with some examples of when one might use these options. But with this in mind, I think we should go with your first option and make these input parameters to `iterative_unfold`, and make the defaults the way we use them.

**Comment by jrbourbeau** [comment]
Can do, thanks for the feedback Zig. 

I have a similar question regarding the Adye error propagation corrections. Right now the default value is `error_type='ACM'` (i.e. Adye corrections are used). We could:

1.  Add a parameter to `iterative_unfold` to specify whether or not to use these corrections or 
2. Could just always use them

**Comment by zhampel** [comment]
Hmmm... Technically the D'Agostini cov calc is not correct, but a first iteration approximation. The only issue I forsee is that for some huge number of causes, or a large set of blocks, the full uncertainty propagation calculation *could* potentially take a long time and bog down the unfolding. Yet, at the same time, the Adye way is the correct way. I say we can just always use the correct version, so your option 2. Do you also agree?

**Comment by jrbourbeau** [comment]
I agree with you. I'll remove the D'Agostini cov calculation and just keep the Adye version. I think it would be premature to worry much about the speed of unfolding for large number of cause bins at this point. 

P.S. I'm thinking about trying to use cython to try and speed up some of the `for`-loops here anyways.
