### ISSUE TITLE
Jeffreys' Prior Calculation

### ISSUE THREAD

**Issue by zhampel** [jrbourbeau/pyunfold#51]
The setup of the Jeffreys' calculation needs to be corrected. It's fine if the cause array is general, but to be a truly Jeffreys' prior, it must use the actual cause array limits. Thus, we need to allow the user to provide cause array definition. If the cause bins are not provided, then we need to make the default be that all bins are of equal probability, i.e. `prior = 1/num_causes`

**Comment by zhampel** [comment]
Also need to make Jeffreys' prior deal with groups.

**Comment by zhampel** [comment]
I've added in a uniform prior as default (1/num_causes) and made Jeffreys' prior require a cause axis as input.

**Comment by zhampel** [comment]
I haven't changed any of the testing suite, so the builds are dying. I'm not sure how you want to handle implementing uniform + jeffreys + user priors in the tests.

**Comment by jrbourbeau** [comment]
Closed by #52
