### ISSUE TITLE
pyunfold not installed in binder tutorial

### ISSUE THREAD

**Issue by juliohm** [jrbourbeau/pyunfold#67]
Hi @jrbourbeau,

I've started reviewing the package for JOSS. Could you please confirm that the binder tutorial should run just fine? I tried executing the first cell in the notebook, but it says that `pyunfold` is not installed.

**Comment by jrbourbeau** [comment]
Good catch @juliohm! I was able to reproduce the same error you got when running the binder tutorial

```python
ModuleNotFoundError: No module named 'pyunfold'
```

I'll update the environment that binder builds to make sure `pyunfold` is actually installed

Thanks for the JOSS review and isssue report!
