### ISSUE TITLE
Unfolding of multidimensional spectra / multidimensional smearing

### ISSUE THREAD

**Issue by fzeiser** [jrbourbeau/pyunfold#89]
I'm trying to unfold a multidimensional spectrum, which is somewhat similar to Fig. 3 in the article on the iterative unfolding method by D*Agostini1995. However, I have troubles getting pyunfold to run on this. I think this is mainly due to the automated checks (and assumptions) on the dimensions. Has anyone tried this before and could help me? What do I need to change in the code of pyunfold?

Here is an example picture for 2 dimensions:
![true_vs_observed](https://user-images.githubusercontent.com/15156776/44665042-3ed54700-aa15-11e8-8cfb-125918a261c6.png)

I started a notebook (again, first trying to work on 2 dimensions), where I try to extend the example in the tutorial into several dimensions. The plots above are created with it.
https://gist.github.com/fzeiser/56c78bb00bfed35652ff1cd000d38108
http://nbviewer.jupyter.org/gist/fzeiser/56c78bb00bfed35652ff1cd000d38108#

I receive following error message:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-8c76aaf5ddc9> in <module>()
     12                                     prior=uni_prior,
     13                                     ts_stopping=0.01, max_iter=100,
---> 14                                     callbacks=[Logger()])
     15 #unfolded_results_rmd = iterative_unfold(data=data_observed,
     16 #                                    data_err=data_observed_err,

/usr/local/lib/python3.5/dist-packages/pyunfold/unfold.py in iterative_unfold(data, data_err, response, response_err, efficiencies, efficiencies_err, prior, ts, ts_stopping, max_iter, cov_type, return_iterations, callbacks)
    160                               ts_func=ts_func,
    161                               max_iter=max_iter,
--> 162                               callbacks=callbacks)
    163 
    164     if return_iterations:

/usr/local/lib/python3.5/dist-packages/pyunfold/unfold.py in _unfold(prior, mixer, ts_func, max_iter, callbacks)
    201 
    202         # Perform unfolding for this iteration
--> 203         unfolded_n_c = mixer.smear(current_n_c)
    204         iteration += 1
    205         status = {'unfolded': unfolded_n_c,

/usr/local/lib/python3.5/dist-packages/pyunfold/mix.py in smear(self, n_c)
     70                        'Response matrix has {} cause bins, while prior '
     71                        'has {} cause bins.'.format(self.cbins, len(n_c)))
---> 72             raise ValueError(err_msg)
     73 
     74         ebins = self.ebins

ValueError: Trying to unfold with the wrong number of causes. Response matrix has 9 cause bins, while prior has 28 cause bins.
```

with the default prior (not specifying anything), the error is basically the same:
```python
ValueError: Trying to unfold with the wrong number of causes. Response matrix has 9 cause bins, while prior has 19 cause bins.
```

**Comment by fzeiser** [comment]
Maybe I have just overlooked that this is included as an example already via "multivariate unfolding"

**Comment by jrbourbeau** [comment]
Hi @fzeiser, thanks for opening up this issue! It looks like one problem here is that the response matrix that's input to `iterative_unfold` needs to be 2-dimensional, but in the above example it is 4-dimensional (with shape `(19, 9, 19, 9)`). With PyUnfold, any response matrix should be 2-dimensional where the first dimension (rows) are effect bins and the second dimension (columns) are the causes bins. 

In the example outlined above, each sample has a true `x` and `y` and an observed `x` and `y`. Since there are 19 `x` bins and 9 `y` bins, altogether there are 171 effects bins and 171 cause bins. One possible way to construct the effects bins is to have the first effect bin contain samples that are in the first x and first y bin, the second effect bin contains samples that are in the first x bin and second y bin, the third effect bin contains samples that are in the first x bin and third y bin, etc. A similar scheme could then be used to define the cause bins. 

With this formatting, the array shapes input into `iterative_unfold` for this problem should be:

- `data.shape = (171, )`
- `efficiencies.shape = (171, )`
- `response.shape = (171, 171)`

**Comment by fzeiser** [comment]
Thanks @jrbourbeau for the clarification. As you pointed out, I unroll should simply transform the matrixes to a 1D shape. I write up a sketch of procedure in two dimensions (and on a 2x2 example matrix), but this is expendable to arb. number of dimensions.

For each cause bin `c_ij`, from the matrix of cause bins
```
  [ [c_aa, c_ab ],
     c_ba, c_bb ]]
```
I create the response matrix (effects matrix) E_ij; so
```
E_aa =  [ [e11, e12 ], or more precisely [ [e_aa_11, e_aa_12 ],
           e21, e22 ]]				        e_aa_21, e_aa_22 ]]

```
Then I unroll the effects matrices to 1D: (eg by `E_aa.reshape(-1)` )
```
 [ [e11, e12 ],     -> [ [e_11, e_12, e_21, e_22 ] ] = E1D_ij
    e21, e22 
```
and do the same unrolling for the causes*:
*being aware of the potential challenges with/without grouping etc., as specified in https://github.com/jrbourbeau/pyunfold/blob/598af28a61bcf17c7d774d1d4d57d3d312bb0e60/docs/source/notebooks/multivariate.ipynb

```
  [ [c_aa, c_ab ], -> [ [c_aa, c_ab, c_ba, c_bb ] ]
     c_ba, c_bb ]]
```
 such that the response matrix will be a 1D array of 1D arrays, so effectively a 2D array:
```
[ [E1D_aa, E1D_ab, E1D_ba, E1D_bb ]]
```
This can be passed together with the other matrices (which are properly reshaped). The results from the unfolding procedure can be reshaped into 2D dimensions again.

Note that for higher dimensions (and bins per dimension), the size of the arrays quickly grows, so one has to take care of what data types are used and so on.

**Comment by jrbourbeau** [comment]
Yeah, exactly! The formatting you outlined above should now work.

**Comment by jrbourbeau** [comment]
I'm going to close this issue because it looks like your original question has been answered. But please feel free to continue this conversation here, or re-open the issue if you run into further related problems!
